### ISSUE TITLE
Writability of SINH, UINH, VSINH, and VUINH when unsupporting corresponding modes

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-count-overflow#3]
Hello, 

Are the SINH, UINH, VSINH, and VUINH of mhpmevent CSRs RW when the corresponding mode unsupported?
For instance, if the S-mode is unsupported, is the mhpmevent.SINH still RW or read-only 0?

Thank you
Best regards,
YenHaoChen

**Comment by YenHaoChen** [comment]
@jscheid-ventana @jjscheel 
Friendly reminder

**Comment by pdonahue-ventana** [comment]
"The mhpmeventn registers are WARL registers" so presumably any bit that's not supported would be hardwired.  Maybe that should be explicit as it is in some other specs. @gfavor

**Comment by gfavor** [comment]
I agree.  The definition of WARL requires that a read of a WARL bit always returns a "legal" value - where "legal" values are "supported" values.  Hence, if the bit's functionality is not supported, then the only "legal" value is zero.

Also note that writing all zeroes to mhpmeventX must represent "no event".  So hardwiring an unsupported bit to one would be inconsistent with this.

**Comment by YenHaoChen** [comment]
Thank you
