### ISSUE TITLE
Can software disable LCOFI by setting mhpmeventx.OF to 1?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-count-overflow#4]
@pdonahue-ventana @gfavor
The OF bit is an overflow status and interrupt disable bit. 
Can software write 1 to the OF bit to disable the interrupt?
![image](https://user-images.githubusercontent.com/39526191/203464901-47ae2de0-d055-4682-9d66-707d1bb922b9.png)
![image](https://user-images.githubusercontent.com/39526191/203464933-5adaf774-3fb5-41eb-8a15-0ddf9b95f4e1.png)
Thank you

**Comment by gfavor** [comment]
This bit, as well as all bits of the mhpmeventX CSRs, is writable by software.  So yes.

**Comment by YenHaoChen** [comment]
Thank you
