### ISSUE TITLE
Does hardware automatically clears OF bit on writing the counter?

### ISSUE THREAD

**Issue by YenHaoChen** [riscv/riscv-count-overflow#7]
Hello @gfavor ,

Does hardware automatically clear OF bit and enables overflow interrupt generation on writing the counter to a starting value? More specifically, will a CSR instruction explicitly writing mhpmcounter3 also implicitly clear mhpmevent3.OF?

![image](https://user-images.githubusercontent.com/39526191/225194242-eeb643c4-6a3a-45ea-9ddd-f8602b520286.png)

Thank you.

**Comment by gfavor** [comment]
On Tue, Mar 14, 2023 at 8:07 PM YenHaoChen ***@***.***> wrote:

> Does hardware automatically clear OF bit and enables overflow interrupt
> generation on writing the counter to a starting value? Or, Is it the
> software's responsibility to clear the OF bit if it wants to enable
> overflow interrupt generation after initializing the counter?
>
Software writes to the CSR simply write all the bits without any special
side effects.  So the latter is correct, i.e. it is software's
responsibility to clear the OF bit when it wants to enable overflow
interrupt generation after initializing the counter.  This allows software
the flexibility as to when it does or doesn't enable overflow interrupt
generation when it writes the CSR.

Greg

**Comment by YenHaoChen** [comment]
Thank you
